service: crud-api
frameworkVersion: '>=4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
  region: eu-west-1
  environment:
    MONGO_URI: ${env:MONGO_URI}
    MONGODB_URI: ${env:MONGO_URI}

functions:
  signup:
    handler: dist/controllers/authController.signup
    events:
      - httpApi:
          method: post
          path: /api/auth/signup
          
  login:
    handler: dist/controllers/authController.login
    events:
      - httpApi:
          method: post
          path: /api/auth/login
          
  createTask:
    handler: dist/controllers/taskController.createTask
    events:
      - httpApi:
          method: post
          path: /api/tasks
          
  getTasks:
    handler: dist/controllers/taskController.getTasks
    events:
      - httpApi:
          method: get
          path: /api/tasks
          
  updateTask:
    handler: dist/controllers/taskController.updateTask
    events:
      - httpApi:
          method: put
          path: /api/tasks/{id}
          
      - httpApi:
          method: patch
          path: /api/tasks/{id}
          
  deleteTask:
    handler: dist/controllers/taskController.deleteTask
    events:
      - httpApi:
          method: delete
          path: /api/tasks/{id}

  updateSortPreference:
    handler: dist/controllers/userController.updateSortPreference
    events:
      - httpApi:
          method: patch
          path: /api/user/sortPreference

package:
  patterns:
    - '!src/**'
    - '!node_modules/.cache/**'
    - '!*.md'
    - '!.git/**'
