allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    // Only override buildDir for projects in the root directory
    if (project.projectDir.parentFile == rootProject.projectDir) {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
